# Minimal configuration for getting started
language: "en-US"

reviews:
  profile: "chill"
  high_level_summary: true
  auto_review:
    enabled: true
    drafts: false
  changed_files_summary: false
  sequence_diagrams: false
